name: tably # you probably want to 'snapcraft register <name>'
version: 'v0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python command-line script for converting .csv data to LaTeX tables  # 79 char long summary
description: |
  Python script for converting .csv data to LaTeX tables.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  tably:
    command: tably

parts:
  tably:
    source: https://github.com/narimiran/tably.git
    source-tag: v0.2
    plugin: python
    stage-packages: [curl] 
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
